### ISSUE TITLE
Exception in thread "main" com.google.inject.CreationException: Unable to create injector

### ISSUE THREAD

**Issue by kse3hi** [eclipse/dash-licenses#223]
**Dash Version:** _org.eclipse.dash.licenses-0.0.1-20230403.055043-775.jar_

**Input**:  _dash_sbom_ content:
```
pypi/pypi/-/aiohttp/3.8.3
pypi/pypi/-/aiosignal/1.3.1
pypi/pypi/-/anytree/2.8.0
```

**Command**:
`java -jar org.eclipse.dash.licenses-0.0.1-20230403.055043-775.jar dash_sbom `
``` 
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInjectingMethod]: RuntimeException: ConnectException
  at LicenseSupport.init(LicenseSupport.java:46)
  at LicenseToolModule.configure(LicenseToolModule.java:57)
  at ClearlyDefinedSupport.licenseService(ClearlyDefinedSupport.java:37)
      \_ for field licenseService
  at LicenseToolModule.configure(LicenseToolModule.java:56)
  at LicenseChecker.clearlyDefinedService(LicenseChecker.java:24)
      \_ for field clearlyDefinedService
  at LicenseToolModule.configure(LicenseToolModule.java:48)

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_METHOD

1 error

======================
Full classname legend:
======================
ClearlyDefinedSupport: "org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport"
ConnectException:      "java.net.ConnectException"
LicenseChecker:        "org.eclipse.dash.licenses.LicenseChecker"
LicenseSupport:        "org.eclipse.dash.licenses.LicenseSupport"
LicenseToolModule:     "org.eclipse.dash.licenses.context.LicenseToolModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:576)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at org.eclipse.dash.licenses.cli.Main.main(Main.java:67)
Caused by: java.lang.RuntimeException: java.net.ConnectException
        at org.eclipse.dash.licenses.http.HttpClientService.get(HttpClientService.java:103)
        at org.eclipse.dash.licenses.http.HttpClientService.get(HttpClientService.java:80)
        at org.eclipse.dash.licenses.LicenseSupport.init(LicenseSupport.java:46)
        at org.eclipse.dash.licenses.LicenseSupport$$FastClassByGuice$$1344954.GUICE$TRAMPOLINE(<generated>)
        at org.eclipse.dash.licenses.LicenseSupport$$FastClassByGuice$$1344954.apply(<generated>)
        at com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:50)
        at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:87)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
        at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:245)
        at com.google.inject.internal.ConstantFactory.get(ConstantFactory.java:34)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
        at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:245)
        at com.google.inject.internal.ConstantFactory.get(ConstantFactory.java:34)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
        at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:245)
        at com.google.inject.internal.Initializer.injectAll(Initializer.java:140)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        ... 5 more
Caused by: java.net.ConnectException
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:561)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at org.eclipse.dash.licenses.http.HttpClientService.get(HttpClientService.java:97)
        ... 32 more
Caused by: java.net.ConnectException
        at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1021)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:179)
        at java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56)
        at java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:369)
        at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:128)
        at java.net.http/jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:93)
        at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Exchange.java:306)
        at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:438)
        at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:343)
        at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:335)
        at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:347)
        at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:388)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
        at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946)
        at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2266)
        at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:378)
        at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:293)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:153)
        at java.base/java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2591)
        at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:246)
        at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:632)
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:540)
        ... 34 more
Caused by: java.nio.channels.UnresolvedAddressException
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:131)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:673)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:165)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:167)
        ... 57 more
```

**Comment by waynebeaton** [comment]
But... that's unrelated to what we're seeing here.

It's failing because it can't connect to our server to get a license list.

Do you have some sort of network proxy stopping external communication?

**Comment by kse3hi** [comment]
HI @waynebeaton ,

Yes, we are using Proxy, after I've added proxy for "socks" it starts to work. 

```
java -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3129 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3129 -Dhttp.nonProxyHosts="localhost|127.0.0.1" -Dhttps.nonProxyHosts="localhost|127.0.0.1" -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=3129 -jar org.eclipse.dash.licenses-0.0.1-20230403.055043-775.jar dash_sbom
```
Unfortunately I got another exception afterwards:
**Input**:  dash_sbom
```
pypi/pypi/-/aiohttp/3.8.3
pypi/pypi/-/aiosignal/1.3.1
pypi/pypi/-/async-timeout/4.0.2
pypi/pypi/-/attrs/22.1.0
pypi/pypi/-/bandit/1.7.4
pypi/pypi/-/black/23.1.0
pypi/pypi/-/build/0.9.0
pypi/pypi/-/cfgv/3.3.1
pypi/pypi/-/charset-normalizer/2.1.1
pypi/pypi/-/click/8.1.3
pypi/pypi/-/cloudevents/1.7.1
pypi/pypi/-/dapr/1.8.3
pypi/pypi/-/deprecation/2.1.0
pypi/pypi/-/distlib/0.3.6
pypi/pypi/-/filelock/3.9.0
pypi/pypi/-/flake8/6.0.0
pypi/pypi/-/frozenlist/1.3.3
pypi/pypi/-/gitdb/4.0.10
pypi/pypi/-/GitPython/3.1.31
pypi/pypi/-/grpc-stubs/1.24.11
pypi/pypi/-/grpcio/1.48.2
pypi/pypi/-/grpcio-tools/1.48.2
pypi/pypi/-/identify/2.5.9
pypi/pypi/-/idna/3.4
pypi/pypi/-/mccabe/0.7.0
pypi/pypi/-/multidict/6.0.2
pypi/pypi/-/mypy/0.991
pypi/pypi/-/mypy-extensions/0.4.3
pypi/pypi/-/mypy-protobuf/3.3.0
pypi/pypi/-/nodeenv/1.7.0
pypi/pypi/-/packaging/23.0
pypi/pypi/-/pathspec/0.10.2
pypi/pypi/-/pbr/5.11.0
pypi/pypi/-/pep517/0.13.0
pypi/pypi/-/pip/22.0.4
pypi/pypi/-/pip-tools/6.10.0
pypi/pypi/-/platformdirs/3.0.0
pypi/pypi/-/pre-commit/2.20.0
pypi/pypi/-/protobuf/3.20.3
pypi/pypi/-/pycodestyle/2.10.0
pypi/pypi/-/pyflakes/3.0.1
pypi/pypi/-/python-dateutil/2.8.2
pypi/pypi/-/PyYAML/6.0
pypi/pypi/-/setuptools/58.1.0
pypi/pypi/-/six/1.16.0
pypi/pypi/-/smmap/5.0.0
pypi/pypi/-/stevedore/4.1.1
pypi/pypi/-/toml/0.10.2
pypi/pypi/-/tomli/2.0.1
pypi/pypi/-/types-protobuf/4.21.0.0
pypi/pypi/-/typing-extensions/4.4.0
pypi/pypi/-/virtualenv/20.20.0
pypi/pypi/-/wheel/0.38.4
pypi/pypi/-/yarl/1.8.1
```

The first invocation:

**Error message:**
```
[main] INFO Querying Eclipse Foundation for license data for 54 items.
[main] INFO Found 1 items.
[main] INFO Querying ClearlyDefined for license data for 53 items.
[main] ERROR Error response from ClearlyDefined 429
Exception in thread "main" java.lang.RuntimeException: Received an error response from ClearlyDefined.
        at org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport.doQueryClearlyDefined(ClearlyDefinedSupport.java:174)
        at org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport.queryClearlyDefined(ClearlyDefinedSupport.java:123)
        at org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport.queryLicenseData(ClearlyDefinedSupport.java:102)
        at org.eclipse.dash.licenses.LicenseChecker.lambda$getLicenseData$3(LicenseChecker.java:52)
        at org.eclipse.dash.licenses.util.Batchifier.batchify(Batchifier.java:77)
        at org.eclipse.dash.licenses.LicenseChecker.getLicenseData(LicenseChecker.java:57)
        at org.eclipse.dash.licenses.cli.Main.lambda$main$5(Main.java:118)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.eclipse.dash.licenses.cli.Main.main(Main.java:100)
```

The second invocation was without errors:
```
[main] INFO Querying Eclipse Foundation for license data for 54 items.
[main] INFO Found 1 items.
[main] INFO Querying ClearlyDefined for license data for 53 items.
[main] INFO Found 53 items.
[main] INFO License information could not be automatically verified for the following content:
[main] INFO
[main] INFO pypi/pypi/-/aiohttp/3.8.3
[main] INFO pypi/pypi/-/bandit/1.7.4
[main] INFO pypi/pypi/-/black/23.1.0
[main] INFO pypi/pypi/-/charset-normalizer/2.1.1
[main] INFO pypi/pypi/-/cloudevents/1.7.1
[main] INFO pypi/pypi/-/deprecation/2.1.0
[main] INFO pypi/pypi/-/filelock/3.9.0
[main] INFO pypi/pypi/-/gitdb/4.0.10
[main] INFO pypi/pypi/-/identify/2.5.9
[main] INFO pypi/pypi/-/idna/3.4
[main] INFO pypi/pypi/-/mypy/0.991
[main] INFO pypi/pypi/-/pathspec/0.10.2
[main] INFO pypi/pypi/-/pbr/5.11.0
[main] INFO pypi/pypi/-/pep517/0.13.0
[main] INFO pypi/pypi/-/pip/22.0.4
[main] INFO pypi/pypi/-/protobuf/3.20.3
[main] INFO pypi/pypi/-/pycodestyle/2.10.0
[main] INFO pypi/pypi/-/pyflakes/3.0.1
[main] INFO pypi/pypi/-/python-dateutil/2.8.2
[main] INFO pypi/pypi/-/tomli/2.0.1
[main] INFO pypi/pypi/-/types-protobuf/4.21.0.0
[main] INFO pypi/pypi/-/typing-extensions/4.4.0
[main] INFO pypi/pypi/-/wheel/0.38.4
[main] INFO
[main] INFO This content is either not correctly mapped by the system, or requires review.
```

**Comment by waynebeaton** [comment]
The HTTP 429 response is in response to the rate limit being exceeded.

This may be the result of frequent calls as you tested.

I've resisted adding code to honour rate limits because we batch requests and don't run into rate limits very often. The algorithm that works around the Pypi error that I describe above makes multiple calls as it tries to narrow down the entry that fails. Even with this, we tend to not run into rate limits.

Regardless... it's time to think harder about how we deal with this. I'll open a separate issue to track this work.
